openapi: 3.1.0
info:
  version: 1.0.0
  title: API SERVER
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Опис вашого додатку
servers:
  - url: https://nodejs-hw-mongodb-ubok.onrender.com
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    Contact:
      $ref: './swagger/components/schemas/Contact.yaml'
paths:
  /contacts:
    get:
      $ref: './swagger/paths/contacts/get.yaml'
    post:
      $ref: './swagger/paths/contacts/post.yaml'
  /contacts/{contactId}:
    get:
      $ref: './swagger/paths/contacts/{id}/get.yaml'
    patch:
      $ref: './swagger/paths/contacts/{id}/patch.yaml'
    delete:
      $ref: './swagger/paths/contacts/{id}/delete.yaml'
